name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  setup:
    runs-on: ubuntu-latest
    outputs:
      python-version: ${{ steps.setup-python.outputs.python-version }}
    steps:
      - name: Checkout repository with LFS
        uses: actions/checkout@v4
        with:
          lfs: true

      - name: Pull LFS files
        run: git lfs pull

      - name: Set up Python
        id: setup-python
        uses: actions/setup-python@v5
        with:
          python-version-file: ".python-version"

      - name: Install just
        uses: extractions/setup-just@v3

      - name: Install uv with caching enabled
        uses: astral-sh/setup-uv@v6
        with:
          enable-cache: true

      - name: Install dependencies
        run: just install

      - name: Minimize uv cache
        run: uv cache prune --ci

  lint:
    runs-on: ubuntu-latest
    needs: setup
    steps:
      - uses: actions/checkout@v4
        with:
          lfs: true
      - name: Run linters
        run: just lint

  typing:
    runs-on: ubuntu-latest
    needs: setup
    steps:
      - uses: actions/checkout@v4
        with:
          lfs: true
      - name: Run type checking
        run: just typing

  tests:
    runs-on: ubuntu-latest
    needs: setup
    steps:
      - uses: actions/checkout@v4
        with:
          lfs: true
      - name: Run tests with coverage
        run: just cov

  check-all:
    runs-on: ubuntu-latest
    needs: [lint, typing, tests]
    steps:
      - uses: actions/checkout@v4
        with:
          lfs: true
      - name: Run final checks
        run: just check-all
